name: '&#60;LivCode&#47;&#62;'
social_github_username:  suhaas-livcd
social_linkedin_username: suhaassrinivas
markdown: kramdown
future: true
kramdown:
  syntax_highlighter: rouge
permalink: /:categories/:slug
plugins:
  - jemoji
  - jekyll-sitemap